version: "3.0"

services:
  haproxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: haproxy:log

    ports:
    - 8080:8080
    - 8000:80
    
    volumes:
    - ./conf/haproxy.anwar.cfg:/etc/haproxy/haproxy.cfg:ro
    - ./logs:/var/log/haproxy
    
    - ./conf/rsyslogs-haproxy.conf:/etc/rsyslog.d/rsyslogs-haproxy.conf
    # - ./conf/logrotate-haproxy.conf /etc/logrotate.d/logrotate-haproxy.conf
    # - ./conf/supervisord-haproxy.conf /etc/supervisor/conf.d/supervisord-haproxy.conf
    # - ./conf/rsyslog.conf /etc/rsyslog.conf
    # - ./conf/supervisord.conf /etc/supervisor/supervisord.conf
  
  myservice:
    image: nginx:latest